### ISSUE TITLE
General Question regarding Cross-attention

### ISSUE THREAD

**Issue by sean-xr** [WalBouss/LeGrad#4]
Thanks for the great work!

Could you expect that your method could also be applied to architecture with cross-attention? Such as CLIP-like models but with cross-attention between text and image encoders.

Thanks for the answer in advance.

**Comment by WalBouss** [comment]
Thanks for your interest in our work! 
Yes, I think it will work to use the method for cross-attention. If you think about it, the attention pooler in SigLIP is really just a cross-attention layer and LeGrad works quite well with SigLIP.

**Comment by sean-xr** [comment]
Thanks for the answer!
